age=c(25,31,23)
height=c(177,163,190)
weight=c(57,69,83)
sex=c("F","F","M")
df=data.frame(Age=age,Height=height,Weight=weight,Sex=sex)
df
names=c("Alex","Lilly","Mark")
row.names(df)=names
df
df2=data.frame(Working=c("Yes","No","No"))
df=cbind(df,df2)
df
class(df$Age)
class(df$Height)
class(df$Weight)
class(df$Sex)
class(df$Working)
mean(df$Height)
BMI=df$Weight/(df$Height/100)**2
BMI
df=cbind(df,BMI)
df
Healthy=df$BMI<25
Healthy
df=cbind(df,Healthy)
df
